# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  buildAndDeploy:
    docker:
      - image: circleci/golang:1.17
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Golang Test 
          command: |
            go test -v ./...
      - run:
          name: Build Golang Server
          command: |
            GOOS=linux GOARCH=amd64 go build -o servertemplate
      - run:
          name: define ECR repository From CircleCI env setting
          command: |
            echo 'export ECR_REPOSITORY_NAME="${AWS_RESOURCE_NAME_PREFIX}"' >> $BASH_ENV
            echo 'export FULL_IMAGE_NAME="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}"' >> $BASH_ENV
      - run:
          name: show current dir
          command: |
            pwd
            ls -a
      - run:
          name: Build image
          command: |
            docker build -f Dockerfile -t $FULL_IMAGE_NAME .
      - run:
          name: Save Docker image as an archive
          command: |
            mkdir docker-image
            docker save -o docker-image/image.tar $FULL_IMAGE_NAME

workflows:
  version: 2
  build-push:
    jobs:
      - buildAndDeploy:
          filters:
            branches:
              only:
                - master
